In [1]:
import numpy as np
import matplotlib.pyplot as plt
from normxcorr2 import normxcorr2
import bpass as bp

In [2]:
o_im1 = plt.imread('bf.tiff')
o_im2 = plt.imread('af.tiff')
rect = [493, 85, 223, 142]
im1 = bp.im2double(o_im1)
im2 = bp.im2double(o_im2)

In [3]:
subimg = o_im1[int(rect[1]):int(rect[1]+rect[3]), int(rect[0]):int(rect[0]+rect[2])]
%matplotlib qt
plt.figure(1)
plt.imshow(subimg,cmap='gray',vmin=0,vmax=0.1*max(o_im1.flatten()))
plt.show()

In [13]:
cc1 = normxcorr2(subimg,o_im1,mode='full')
cc2 = normxcorr2(subimg,o_im2,mode='full')
idm1 = np.where(cc1 == np.amax(np.abs(cc1)))
idm2 = np.where(cc2 == np.amax(np.abs(cc2)))

    


In [17]:
#[xpeak1,ypeak1] = np.unravel_index(idm1,np.shape(cc1),order='F')
#[xpeak2,ypeak2] = np.unravel_index(idm2,np.shape(cc2),order='F')

    
xdrift = idm2[1]-idm1[1]
ydrift = idm2[0]-idm1[0]
    
np.array([xdrift[0],ydrift[0]])

array([34,  3], dtype=int64)

0.9999999999999997 0.9098501891133842


(array([226], dtype=int64), array([715], dtype=int64))

(array([229], dtype=int64), array([749], dtype=int64))

array([9.09850189e-01, 8.89398724e-01, 8.80398114e-01, ...,
       3.17143456e-08, 3.16612662e-08, 7.73414918e-09])

0.909850189113384